[package]
edition = "2021"
name    = "voyager-client-module-cometbls"
version = "0.1.0"

[dependencies]
ark-bn254                   = { version = "0.4", default-features = false, features = ["curve"] }
ark-serialize               = "0.4.2"
clap                        = { workspace = true, features = ["default", "derive", "env", "error-context"] }
cometbft-rpc                = { workspace = true }
cometbls-light-client-types = { workspace = true, features = ["proto", "ethabi"] }
dashmap                     = { workspace = true }
enumorph                    = { workspace = true }
futures                     = { workspace = true }
jsonrpsee                   = { workspace = true, features = ["macros", "server", "tracing"] }
macros                      = { workspace = true }
num-bigint                  = { workspace = true }
prost                       = { workspace = true }
protos                      = { workspace = true }
serde                       = { workspace = true, features = ["derive"] }
serde-utils                 = { workspace = true }
serde_json                  = { workspace = true }
thiserror                   = { workspace = true }
tokio                       = { workspace = true }
tracing                     = { workspace = true }
tracing-subscriber          = { workspace = true }
unionlabs                   = { workspace = true }
voyager-message             = { workspace = true }
voyager-vm                  = { workspace = true }

[dev-dependencies]
hex.workspace = true
