[package]
authors      = ["Hussein Ait Lahcen <hussein.aitlahcen@gmail.com>"]
edition      = { workspace = true }
license-file = { workspace = true }
name         = "ucs01-relay"
publish      = false
repository   = { workspace = true }
version      = "1.0.1"

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
library = []

[dependencies]
base58             = { version = "0.2" }
cosmwasm-schema    = { version = "2.1.0" }
cosmwasm-std       = { version = "2.1.0", features = ["stargate", "cosmwasm_2_1", "abort"] }
cw-controllers     = { version = "2.0.0" }
cw-storage-plus    = { version = "2.0.0" }
cw2                = { version = "2.0.0" }
dlmalloc           = { workspace = true, features = ["global"] }
ethabi             = { workspace = true }
go-parse-duration  = { workspace = true }
hex                = { workspace = true }
prost              = { workspace = true }
protos             = { workspace = true }
schemars           = { workspace = true }
semver             = "1"
serde              = { workspace = true, features = ["derive"] }
serde-json-wasm    = { workspace = true }
serde-utils        = { workspace = true }
sha2               = { workspace = true }
thiserror          = { workspace = true }
token-factory-api  = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
ucs01-relay-api    = { workspace = true }
unionlabs          = { workspace = true }

[dev-dependencies]
cw-multi-test = { git = "https://github.com/CosmWasm/cw-multi-test.git", rev = "e1a2f587c7f9d723444ec93ad8fa48f1d88b65bc", features = ["stargate", "staking"] }
